### PR TITLE
feat: support folders && guess extension

### PR DESCRIPTION
**Pull request by iam4x**
* Add support to require folder statements, will search for index.[ext] files
* Fix no extensions relative require statement resolve, try to guess the correct file without extension.

### CODE REVIEW

**Comment by AsaAyers** [comment]
Can you provide an example of where this is needed? It seems like `resolve` should already handle this situation.

**Comment by iam4x** [comment]
## First case

Project structure:

```
- navbar/index.jsx
- app.jsx
```

in app.jsx:

```javascript
import Navbar from './navbar'
```

* now: CMD + Click on `./navbar` will resolve to -> `navbar.js` 
* after: it resolve to the correct file `./navbar/index.jsx`

## Second case


Project structure:

```
- navbar.jsx
- app.jsx
```
in app.jsx:

```javascript
import Navbar from './navbar'
```

* now: resolve to `./navbar.js`
* after: resolve to `./navbar.jsx`

**Comment by AsaAyers** [comment]
You actually just need to add jsx to the list of extensions. `resolve` already handles all of this automatically.

selection_026

**Comment by iam4x** [comment]
fail

Should it be on README.md?

**Comment by AsaAyers** [comment]
Yea, the readme definitely needs work. I need to take some time to explain what this project does and doesn't do and why.

**Comment by AsaAyers** [comment]
I have added it in the form of an FAQ in the readme. Please let me know if you think it needs anything else.

**Comment by iam4x** [comment]
Perfect, seems good to me :+1:

**Pull request closed without merging**
