### PR TITLE
Add custom resolvers to allow projects to handle things like webpack aliases

### LINKED ISSUE #25: improve resolving path (for webpack alias)
Hello, nice extenstion, but i'am have question - can you improve resolving path?
For sublime text we have this plugin: https://github.com/titoBouzout/Open-Include
it works with webpack alias (for example: import { test } from 'utils/test.js' } 

```
Resolving:

Will try to resolve to:

Absolute path to URL (e.g. https?://...)
Relative to current view
Relative to current view minus 1 folder
Relative to current view minus 2 folders
Relative to project folders
Relative to project folders minus 1 folder
Relative to project folders minus 2 folders
Absolute path
If everything else fails will also look into:

Relative to the folder of all opened views
Relative to all sub-folders
Relative to all parent folders
```

### LINKED ISSUE #46: Make this work with meteor?
Hi guys,

I really love the idea of this package, but can **not** make it work with meteor. ﻿:-(

My meteor-directory-structure looks like:
```
./  // root
/src/* // sources
/src/imports/modules/*  // modules
```

So an import might look like
```
import { Permissions } from '/imports/modules/permissions/lib/permissions.js'
```

When I know click on ``Permissions`` in the code, I get an "module /imports/modules/permissions/lib/permissions.js not found"-error.

**Any ideas how to solve this? It would be such a timesaver to get this to work!!**

### LINKED ISSUE #47: Unable to resolve project root relative imports
I'm using js-hyperclick on my meteor project.
The hyperclick works fine on imports with relative path is used. (like `import {something}  from './something.js';`)   
But it does not work if the import statement is as follows:  
`import '/imports/ui/components/partials/sidebar.js'`

The `imports` folder is inside the project's root directory, not on systems root (`/`) directory.
Is there any option on js-hyperclick to work with these kind of imports?

### LINKED ISSUE #54: Webpack resolver alias dosen't work for js-hyperclick?
When i have defined the alias like 

```js
resolve: {
    extensions: ['', '.js', '.vue'],
    alias: {
      vue: 'vue/dist/vue.js',
      components: path.resolve(__dirname, '../app/components')
    }
  },
```

and then use it in modules like this:

```js
import Ratings from 'components/ratings/ratings';
```

and when i use cmd+click to go-to-declaration,it throw an error which means the alias didn't work.

image

### LINKED ISSUE #58: [idea] Aliases for moduleRoots
Hi and thx for a good tool!
I like to use webpack aliases in my Vue projects (for example: https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L21-L29),
but when I trying use something like `import Module from '@/myComponent/file'`, I get error `module @/myComponent/file was not found`.  
And Yes, I have `moduleRoots` in my package.json. It work perfect for other cases.

May be possible, make some aliases in `moduleRoots`? For example: 
```json
{
"moduleRoots": [ "src/", {"@": "src/components/"} ]
}
```

### LINKED ISSUE #78: Does not support aliases
We have babel.rc in our project with aliases
```
"plugins": [
		"transform-decorators-legacy",
		"transform-class-properties",
		["module-resolver", {
			"root": ["./src"],
			"alias": {
				"app": "js",
				"api": "js/api",
			}
		}]
	]
```
I can solve this partially. E. g. imports like `import {SomeApi} from 'api'` by specifying `moduleRoots` in package.json, but `import {myFunc} from 'app/utils'` won't work, since app is an aliase for js.

### LINKED ISSUE #92: useing in *.vue,if had a '@' js-hyperclick  not work!!
<!--
Please go read the FAQ in this project's README.md before opening your issue.
--!>
like this , import api from '@/api/Api.js'

if you had '@' ,the js-hyperclick is not useful,could you reslove it ?

### LINKED ISSUE #97: Does not resolve and follow modules with webpack aliases
For example, in my `webpack.config.js` file if I specify...

```js
resolve: {
  alias: {
    '~': path.resolve(__dirname, 'src')
  }
}
```

I'd like to be able to click into an `import` statement like this...

```js
import MyComponent from '~/components/MyComponent'
```

However currently it says that it cannot resolve `~/components/MyComponent`.

### PR DESCRIPTION
**Pull request by AsaAyers**
One of the most popular requests in this repo has been to support Webpack Aliases and other non-standard resolution strategies. This PR is expanding the functionality of `moduleRoots` to allow you to write a custom resolver for your own project. If you want to `require()` your webpack config and read the aliases, you can do that in version 1.15.

## moduleRoots

If you have configured your project to avoid `../` in your imports, you can
configure js-hyperclick using `moduleRoots` in your `package.json`. The
configuration belongs there and not in Atom because it is specific to your
project.

For most use cases, you just need to specify the folders to search.
If you want `import 'foo'` to resolve to `src/lib/foo`, just drop this in your `package.json`.

```json
"moduleRoots": [ "src/lib" ],
```

If you're using something more advanced like module aliases you can implement
your own custom resolver. Instead of pointing `moduleRoots` to a folder, just
point it to a JavaScript file and `js-hyperclick` will `require()` and use it [*][security].

While `js-hyperclick` doesn't use these kinds of features in practice, I have
configured them as an example and to validate functionality.

1. moduleRoots configuration in [package.json][moduleRoots]
2. [custom-resolver.js][custom-resolver.js]
3. [spec/fixtures/moduleRoots.js][fixture-moduleRoots]

## Custom Resolver Security

Custom resolvers run inside Atom and extend the functionality of
`js-hyperclick`. This means there is some risk that you could checkout a project
that contains a malicious custom resolver. In order to mitigate this risk, when
`js-hyperclick` encounters a new resolver it will open it and ask if you want to
trust it. Whether you trust or distrust the resolver, `js-hyperclick` stores
that hash so you don't get prompted when switching between branches of a
project, or if you have use the exact same resolver code across multiple
projects.

trust-resolver

Fixes #97 
Fixes #92
Fixes #78 
Fixes #58 
Fixes #54
Fixes #47
Fixes #46
Fixes #25

[moduleRoots]: https://github.com/AsaAyers/js-hyperclick/blob/0e4112b/package.json#L8-L11
[custom-resolver.js]: https://github.com/AsaAyers/js-hyperclick/blob/0e4112b/custom-resolver.js
[fixture-moduleRoots]: https://github.com/AsaAyers/js-hyperclick/blob/0e4112b/spec/fixtures/moduleRoots.js
[security]:https://github.com/AsaAyers/js-hyperclick#custom-resolver-security

### CODE REVIEW

**Comment by AsaAyers** [comment]
https://github.com/AsaAyers/js-hyperclick/blob/6240dc8dd738371d380a1c875f543887ae5eb65d/spec/fixtures/moduleRoots.js#L8-L9

https://github.com/AsaAyers/js-hyperclick/blob/6240dc8dd738371d380a1c875f543887ae5eb65d/custom-resolver.js#L28-L32

**Comment by boltcoder** [comment]
It'd be great if you could support webpack aliases fully. Currently your code doesn't support named aliases. 
eg: projects usually have aliases as following

```
{
"myAppContainer": "./src/containers/",
"myAppComponents": "./src/components/",
}
```
And while importing this is how they are imported
`import MainAppContainer from 'myAppContainer/MainApp';`

**Comment by AsaAyers** [comment]
I don't support reading the aliases from Webpack's config, but you can
configure js-hyperclick to match your config.

**Comment by boltcoder** [comment]
aah. I'm not sure if I can achieve js-hyperclick to match to the above use case. unless I'm missing something. Would be great if you can help me.

**Comment by AsaAyers** [comment]
If your prefix just matched the folder name, then you'd just need `"moduleRoots": [ 'src' ]` in your package.json and you'd be done. `import MainAppContainer from 'myAppContainers/MainApp';` will give you `src/MyAppContainers/MainApp`.

But since you decided not make them match anything you need a custom resolver. In `package.json`
```
  "moduleRoots": [
    "custom-resolver.js"
  ],
```

I just put this together from the [`custom-resolver`](https://github.com/AsaAyers/js-hyperclick/blob/master/custom-resolver.js#L22-L26) that this project has as example for building your own.

```js
const path = require('path')
export default function customResolver({ basedir, moduleName }) {
  // You can use whatever strategy you want to convert your modules
  const [prefix, ...rest] = moduleName.split("/")
  switch (prefix) {
    case "myAppContainers": return path.join(__dirname, "./src/containers/", rest.join(path.sep))
    case "myAppComponents": return path.join(__dirname, "./src/components/", res.join(path.sep))
  }
}
```

**Pull request merged**
