### PR TITLE
Use .js-hyperclick.json config file and cache moduleRoots lookup

### PR DESCRIPTION
**Pull request by avaly**
I've recently run into this issue on a large project with multiple contributors which are not all using Atom. Using `package.json` as a configuration option for editor-specific plugins was frowned upon.

It may be useful to have the `moduleRoots` configuration option in a separate config file, in order not to pollute `package.json` with Atom specific config. 

Use a `.js-hyperclick.json` file with the following content:

```json
{ "moduleRoots": [ "src/lib" ] }
```

Together with this, this PR adds caching for reading the contents of `package.json` and `.js-hyperclick.json`.

### CODE REVIEW

**Comment by AsaAyers** [comment]
I fought against module roots for about a year, and in the end finally agreed to implement it. I'm not going to fragment this further by having some people use `package.json` to configure it and others use `.js-hyperclick.json`, and other people still want it to be locally configured in Atom's preferences. 

From the FAQ:

## I configured {babel,eslint,flow,webpack,etc} to avoid '../' in my imports. How can I configure `js-hyperclick`?

First, I think it's a bad idea to do that and I never configure my projects this
way. In a twitter conversation to see if we could standardize this across
projects some good points were made:

> @nodkz the module loader is locked (in node anyways) so any feature additions should be rejected
>
> -[@evanhlucas](https://twitter.com/evanhlucas/status/771750602967703561)

and

> @nodkz @left_pad @izs @slicknet @zpao I think this is at odds with Node resolution mechanism so it likely won’t happen.
>
> -[@dan_abramov](https://twitter.com/dan_abramov/status/771741318129324032)

If you're still set on custom module directories, there is a way to configure
it. If you keep your common modules in `src/lib` you can add this to your
`package.json`:

**Comment by avaly** [comment]
Please consider at least extracting the caching part out of my branch and integrate into master.

**Comment by avaly** [comment]
Would you consider moving the `moduleRoots` from the `package.json` to the `project-manager` config? See https://github.com/avaly/js-hyperclick/tree/feature/project-manager-config - I'm not gonna PR it if you are not interested.

**Comment by AsaAyers** [comment]
No, I don't want to have to depend on a specific other package for that functionality and I am not going to support multiple configuration locations. 

I've learned over the years that no matter how configuration works people are going to disagree with the implementation. When I managed CoffeeLint the configuration could be `coffeelint.json` or a `coffeeLintConfig` property in `package.json` ([original PR][153]). Some people didn't like that the config [wasn't a hidden file][145]. Supporting multiple configuration locations means having to deal with deciding what order each config should be read to determine priority. For this project I have decided that there is exactly 1 way to configure project-specific configuration options, and that is through `package.json`.

As for the caching, can you show me benchmarks showing the current implementation is a problem that needs to be solved? The module configuration isn't read until after you have clicked, and it only loads it as a last resort when all else has failed.

[153]: https://github.com/clutchski/coffeelint/pull/153
[145]: https://github.com/clutchski/coffeelint/issues/145#issuecomment-39281562

**Pull request closed without merging**
